spring:
  application:
    name: authserver
  profiles:
    default: dev
  jpa: # jpa settings
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  time:
    accessTokenExpireTime: 5
    refreshTokenExpireTime: 30

